# frozen_string_literal: true

# fova Homebrew formula — REFERENCE TEMPLATE ONLY.
#
# The live formula in alvarogonjim/homebrew-tap (the user-facing tap) is
# auto-generated on every release by goreleaser's `brews:` block; see
# .goreleaser.yaml and docs/RELEASING.md. The fields below — url, sha256,
# version — are bumped by goreleaser on each tag; the values committed here
# are placeholders. Do not edit this file expecting it to ship to users.

class Fova < Formula
  desc "TUI agent for de novo protein design"
  homepage "https://github.com/alvarogonjim/fova"
  version "0.5.0"
  license "AGPL-3.0-or-later"

  on_macos do
    on_arm do
      url "https://github.com/alvarogonjim/fova/releases/download/v0.5.0/fova_0.5.0_darwin_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/alvarogonjim/fova/releases/download/v0.5.0/fova_0.5.0_darwin_amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/alvarogonjim/fova/releases/download/v0.5.0/fova_0.5.0_linux_arm64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
    on_intel do
      url "https://github.com/alvarogonjim/fova/releases/download/v0.5.0/fova_0.5.0_linux_amd64.tar.gz"
      sha256 "0000000000000000000000000000000000000000000000000000000000000000"
    end
  end

  def install
    bin.install "fova"
  end

  test do
    assert_match(/^fova /, shell_output("#{bin}/fova version"))
  end
end
